version: '3.8'

services:
  nginx: 
    # Starts services in dependency order
    depends_on: 
      - server
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      # Expose 80 from container as 8008 externally
      - "8008:80"

  server: 
    build:
      context: ./server
    volumes:
      # Mounts the "server" directory from the host to the "/src" directory in the container
      - ./server:/src
      - /src/node_modules
    ports:
      - $SERVER_PORT:$SERVER_PORT

  client:
    stdin_open: true
    # Fix for hot reload for React apps inside of containers
    environment: 
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./client
    volumes:
      - ./client:/src
      - /src/node_modules
    ports: 
      - $CLIENT_PORT:$CLIENT_PORT